In [39]:
#Importamos la biblioteca pandas bajo el alias 'pd'
import pandas as pd

In [40]:
#Ej1: Cargamos en un dataframe panda todos los datos del csv Pokemon
#Usamon la funcion read_csv
pokemon = pd.read_csv("15_pokemon.csv")
#Mostramos los datos almacenados
pokemon

,pokemonID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [41]:
#Ej2: Realizamos un filtrado de los datos según los valores de dos de sus columnas
#En este caso mostraremos todos los pokemon legendarios de una generacion concreta, siendo esta elegida por el ususario
gen = int(input('Introduce generacion de la que deseas ver sus legendarios: '))
#Creamos nuevo dataframe donde solo se almacenen los pokemon legendarios de dicha generacion
legplan = pokemon[(pokemon['Generation'] == gen) & (pokemon['Legendary'])]
#Finalmente mostramos el nuevo dataframe
legplan[['Name', 'Generation', 'Legendary']]

Introduce generacion de la que deseas ver sus legendarios: 5

                         Name  Generation  Legendary
553                   Victini           5       True
699                  Cobalion           5       True
700                 Terrakion           5       True
701                  Virizion           5       True
702   TornadusIncarnate Forme           5       True
703     TornadusTherian Forme           5       True
704  ThundurusIncarnate Forme           5       True
705    ThundurusTherian Forme           5       True
706                  Reshiram           5       True
707                    Zekrom           5       True
708   LandorusIncarnate Forme           5       True
709     LandorusTherian Forme           5       True
710                    Kyurem           5       True
711        KyuremBlack Kyurem           5       True
712        KyuremWhite Kyurem           5       True

In [42]:
#Ej3p1: Construimos un nuevo dataframe identico al original, pero al que añadiremos nuevas columna numericas que dependan de las ya existentes
newPokemon = pokemon.copy()
#En este caso añadiremos dos columnas nuevas, que representaran el total de ataque y el total de defensa
#Para ello se sumaran las columna 'Attack' y 'Sp. Atk' para el total de ataque
newPokemon['totAtaque']=pokemon['Attack']+pokemon['Sp. Atk']
#Y 'Defense' y 'Sp. Def' para el total de defensa
newPokemon['totDefensa']=pokemon['Defense']+pokemon['Sp. Def']
#Ademas añadimos una tercera columna que nos indica si el pokemon es mas atacante o defensivo segun el valor de las dos nuevas columnas
#Para ello usamos la funcion apply() que efectuara fila por fila la funcion lambda, la cual se encarga de comprobar si es mayor la columna totAtaque o totDefensa
#axis=1 indica al metodo apply que la funcion debe efectuarse a cada fila individualmente
newPokemon['modoJuego'] = newPokemon.apply(lambda row: 'Atacante' if row['totAtaque'] >= row['totDefensa'] else 'Defensivo', axis=1)
#Finalmente mostramos el nuevo dataframe
newPokemon

,pokemonID,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,totAtaque,totDefensa,modoJuego
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,114,114,Atacante
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,142,143,Defensivo
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,182,183,Defensivo
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,222,243,Defensivo
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,112,93,Atacante
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,200,300,Defensivo
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,320,220,Atacante
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,260,190,Atacante
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,330,190,Atacante
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,240,210,Atacante

In [43]:
#Ej3p2: Finalmente agrupamos todos los datos segun un dato relevante
#En este caso creamos un nuevo dataframe donde agrupamos los pokemon segun su tipo principal
#Ademas .size() se encarga de contar cuantos hay en total de cada, lo cual se almacena en una nueva columna
#que se llamara 'Total' gracias al reset del nombre de la columna de conteo
tipoPrinc = pokemon.groupby('Type 1').size().reset_index(name='Total')
#Por otro lado, .sort_values() se encarga de ordenar los valores segun la columna 'Total' de forma ascendente
tipoPrinc = tipoPrinc.sort_values(by='Total', ascending=True)
#Para terminar mostramos el nuevo dataframe
tipoPrinc

      Type 1  Total
7     Flying      4
4      Fairy     17
11       Ice     24
5   Fighting     27
16     Steel     27
13    Poison     28
1       Dark     31
8      Ghost     32
2     Dragon     32
10    Ground     32
3   Electric     44
15      Rock     44
6       Fire     52
14   Psychic     57
0        Bug     69
9      Grass     70
12    Normal     98
17     Water    112